ln -s /home/svankina/wksp/dotfiles/bash_aliases /home/svankina/.bash_aliases
ln -s /home/svankina/wksp/dotfiles/bashrc /home/svankina/.bashrc
ln -s /home/svankina/wksp/dotfiles/pdbrc /home/svankina/.pdbrc
ln -s /home/svankina/wksp/dotfiles/pythonrc /home/svankina/.pythonrc
ln -s /home/svankina/wksp/dotfiles/tmux.conf /home/svankina/.tmux.conf
ln -s /home/svankina/wksp/dotfiles/vimrc /home/svankina/.vimrc
ln -s /home/svankina/wksp/dotfiles/xinitrc /home/svankina/.xinitrc
ln -s /home/svankina/wksp/dotfiles/zshrc /home/svankina/.zshrc
ln -s /home/svankina/wksp/dotfiles/config/i3/config /home/svankina/.config/i3/config
